### ISSUE TITLE
Board testing TODO list

### ISSUE THREAD

**Issue by rgmarosi** [rgmarosi/JTAG-Permutator#1]
- [ ] blinky test code for all LEDs
  - [x] verify 24.5MHz oscillator is default, then switch to 48MHz oscillator from now on
  - [x] verify blink frequency with oscilloscope
  - [ ] figure out source of weak glow for idle LEDs (weak pull-ups? open-drain leakage current?)
- [ ] get USB-serial terminal communication working for ease of debugging
   - [x] Periodically transmit strings to serial console
   - [ ] Receive and parse strings from serial console.
- [ ] buck voltage regulator test code
  - [ ] verify output voltage for all 16 settings
  - [ ] measure output impedance of disabled regulator
- [ ] ADC test code
  - [ ] configure internal voltage reference for 2.4V or 1.65V
  - [ ] measure target voltage rail with ADC (USB debugging and working regulator needed)
- [ ] level shifter IO test code
  - [ ] test output and input of shifter interface (loopback testing might be a good idea)
